/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Confetti: typeof import('./components/Confetti.vue')['default']
    Default: typeof import('./layouts/Default.vue')['default']
    Description: typeof import('./components/Description.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Headline: typeof import('./components/Headline.vue')['default']
    Tag: typeof import('./components/Tag.vue')['default']
    Tags: typeof import('./components/Tags.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
  }
}
